version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - game-service
    networks:
      - quadradinho-net

  game-service:
    build: ./game-service
    ports:
      - "8000:8000"
    volumes:
      - ./game-service:/var/www
    depends_on:
      - db
    networks:
      - quadradinho-net

  db:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: quadradinho-game
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - quadradinho-net

volumes:
  db_data:

networks:
  quadradinho-net:
    driver: bridge
